<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Dashboard</name>
   <tag></tag>
   <elementGuidId>93ba2a4f-df25-4a7f-8750-b623f88a5cef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div[2]/div/div/div/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.pr-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3ee40f97-4263-49a5-ae1c-d158be45e267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pr-4</value>
      <webElementGuid>fb003f44-fd04-476a-92a0-cd3863131226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard:</value>
      <webElementGuid>4ec1f80d-6ef2-4099-a21a-f37bda835e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;contentSecton&quot;]/div[@class=&quot;mainContent&quot;]/div[@class=&quot;col-md-12 pt-1 px-0&quot;]/div[@class=&quot;contentSection&quot;]/div[@class=&quot;col-md-12&quot;]/div[1]/div[@class=&quot;customTabs&quot;]/label[@class=&quot;pr-4&quot;]</value>
      <webElementGuid>6ae655df-c5f2-4c89-85c2-1b3dca8d4d88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div/div/div/div/div/label</value>
      <webElementGuid>4d1e17f7-aada-4dcd-a288-ed7f701b64e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hurray !'])[1]/following::label[1]</value>
      <webElementGuid>9c6c11a3-1744-46dc-a232-417f2dec1778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventory'])[1]/preceding::label[1]</value>
      <webElementGuid>2464e3ef-1c22-43a7-896f-ce391dfbb248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order'])[1]/preceding::label[2]</value>
      <webElementGuid>9edec863-4151-4edf-a674-7ae3396149fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboard:']/parent::*</value>
      <webElementGuid>5c836ca9-8160-463c-8fc5-975b9f8f1939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/label</value>
      <webElementGuid>ceac1610-c06b-44a9-b146-2d68951078ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Dashboard:' or . = 'Dashboard:')]</value>
      <webElementGuid>4c0460c3-08dd-4b85-b77e-3e92ec0b5a9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
