<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>54542a97-afc9-462e-bc6a-87eebb29ec0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ant-avatar.ant-avatar-circle.ant-avatar-icon > svg > path</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>1a550282-a547-4179-bbe6-7c6f3caf4244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#FFB74D</value>
      <webElementGuid>42b21758-cb38-4adb-99a0-a6db09675b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M33,13c0-7.6-18-5-18,0c0,1.1,0,5.9,0,7c0,5,4,9,9,9s9-4,9-9C33,18.9,33,14.1,33,13z</value>
      <webElementGuid>29f4f394-7dd6-47eb-9b40-7a5bee7738d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/header[@class=&quot;ada-admin-header&quot;]/section[@class=&quot;avatarUserSection&quot;]/a[@class=&quot;ant-dropdown-trigger ant-dropdown-link ant-dropdown-open&quot;]/span[@class=&quot;ant-avatar ant-avatar-circle ant-avatar-icon&quot;]/svg[1]/path[1]</value>
      <webElementGuid>cbfb6593-8fe7-48a4-8cf1-dcb4243e54d6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
